### ISSUE TITLE
eRechnung issue when opening the plugin

### ISSUE THREAD

**Issue by keiner99** [austriapro/ebinterface-word-plugin#1]
Hello,

i got an issue, when i open the eRechnung plugin, i tested it on Win7+Office10; Win7+Office16 and Win10+Office16 and version 4.3

Everytime the same error message appears, when i open the eRechnung.dotx :
![unbenannt](https://user-images.githubusercontent.com/9336808/38305772-62867404-380e-11e8-8f0f-8be6204f078e.PNG)

can you help me with this problem?

Best regards,
keiner99

**Comment by digitalsigi** [comment]
Plse Update to latest Version. If Problem persists:
Please attach the Log. It can be found in Documents\eRechnung\Log.

**Comment by digitalsigi** [comment]
Hi,
LOG does not start as expected. 
- How did you start the Application? -> You need to double click the word template file.
- LOG shows that it is not possible to create a TLS channel to query Release info from Github. There may be a network issue at your Location. Firewall?

**Comment by keiner99** [comment]
Hello,

I started the application with the word template.  There is no firewall in the network, windows firewall is turned off.

Best regards,
keiner99

**Comment by digitalsigi** [comment]
Retestet it, and accepted the bug.

**Comment by digitalsigi** [comment]
Resolution in Rel. 4.3.0.6, plse update

**Comment by keiner99** [comment]
Danke, funktioniert wieder! LG keiner99
